pipeline {
 tools {
   maven "M3"
 }
 agent any
 stages {
   stage("Preparation") { 
     steps {
       git 'https://github.com/codeurjc/expoqa19.git'
     }
   }
   stage("Create jar") {
       steps {
           sh "cd webapp2; docker-compose build"
       }
   }
   stage("Start app") {
    steps {
     sh "cd webapp2; docker-compose up -d"
    }
   }
   stage("Test") {
     steps {
       sh "cd webapp2; mvn test"
     }
   }
 } 
 post {
    always {

      ws("webapp2") {

        sh "docker-compose logs"
      
        sh "docker-compose logs > all-logs.txt"
        archive "webapp2/all-logs.txt"
      
        sh "docker-compose logs web > web-logs.txt"
        archive "webapp2/web-logs.txt"
      
        sh "docker-compose logs db > db-logs.txt"
        archive "webapp2/db-logs.txt"
      
        sh "docker-compose down"
      
        junit "target/*-reports/TEST-*.xml"

      }
    }
    success {
      archive "webapp2/target/*.jar"
    }
 }
}
