apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
    nodePort: 3306
  selector:
    io.kompose.service: db
  type: NodePort
status:
  loadBalancer: {}
