apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f expoqa-sut-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: "38080"
    port: 38080
    targetPort: 8080
    nodePort: 38080
  type: NodePort
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
