apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
spec:
  ports:
  - name: "38080"
    port: 38080
    targetPort: 8080
    nodePort: 38080
  selector:
    app: web
  type: NodePort
status:
  loadBalancer: {}
