apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f expoqa-sut-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_PASSWORD
          value: pass
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://db/test
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        image: expoqa19/webapp2:v1
        name: web
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
