version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    ports:
      - "39200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ES_JAVA_OPTS=-Xmx3g -Xms3g
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    ports:
      - "35601:5601"
volumes:
    elasticsearch-data:
      driver: local

