apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: db
    io.elastest.service: db
  name: db-deploy
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: db
        io.elastest.service: db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: test
        - name: MYSQL_ROOT_PASSWORD
          value: pass
        image: mysql:5.5.62
        name: db
        resources: {}
      restartPolicy: Always
status: {}