apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: web
    io.elastest.service: web
  name: web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: web
        io.elastest.service: web
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_PASSWORD
          value: pass
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://db:33306/test
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        image: expoqa19/webapp2:v1
        name: web
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
