pipeline {
 tools {
   maven "M3"
 }
 agent any
 stages {
   stage("Preparation") { 
     steps {
       git 'https://github.com/codeurjc/expoqa19.git'
     }
   }
   stage("Create jar") {
       steps {
           sh "cd webapp1; mvn package"
       }
   }
   stage("Start app") {
    steps {
     sh "java -jar webapp1/target/webapp1-0.0.1-SNAPSHOT.jar --server.port=9000 > out.log & echo \$! > pid"
    }
   }
   stage("Test") {
     steps {
       sh "cd webapp1; mvn verify"
     }
   }
 } 
 post {
    always {
      sh "kill \$(cat pid)"
      archive "out.log"
      junit "webapp1/**/target/*-reports/TEST-*.xml"
    }
    success {
      archive "webapp1/target/*.jar"
    }
 }
}
