pipeline {
 tools {
   maven "M3"
 }
 agent any
 stages {
   stage("Preparation") { 
     steps {
       git 'https://github.com/codeurjc/expoqa19.git'
     }
   }
   stage("Create jar") {
       steps {
           sh "cd webapp1; mvn package -DskipTests=true"
       }
   }
   stage("Start app") {
    steps {
     sh "java -jar webapp1/target/webapp-0.0.1-SNAPSHOT.jar > out.log & echo \$! > pid"
    }
   }
   stage("Test") {
     steps {
       sh "cd webapp1; mvn test"
     }
   }
 } 
 post {
    always {
      junit "webapp1/**/target/surefire-reports/TEST-*.xml"
      sh "kill \$(cat webapp/target/pid)"
      archive "out.log"
    }
    success {
      archive "webapp1/target/*.jar"
    }
 }
}
